// Built-in practice material. All dialogues are original (copyright-safe).
// Each sentence: { en, ipa, zh }. IPA is a learning aid (approximate).
// Later these can be supplemented by user-imported text or YouTube captions.
const LESSONS = [
  {
    id: 'daily-greetings',
    title: '日常 · 打招呼与寒暄',
    level: '初级',
    sentences: [
      { en: "Hey, it's been a while! How have you been?", ipa: "/heɪ ɪts bɪn ə waɪl haʊ hæv juː bɪn/", zh: "嘿，好久不见！你最近怎么样？" },
      { en: "Pretty good, thanks. I've been really busy with work.", ipa: "/ˈprɪti ɡʊd θæŋks aɪv bɪn ˈrɪli ˈbɪzi wɪð wɜːrk/", zh: "挺好的，谢谢。我最近工作很忙。" },
      { en: "I totally get that. We should grab a coffee sometime.", ipa: "/aɪ ˈtoʊtəli ɡet ðæt wi ʃʊd ɡræb ə ˈkɔːfi ˈsʌmtaɪm/", zh: "我完全理解。我们改天该一起喝杯咖啡。" },
      { en: "Sounds great. How about this weekend?", ipa: "/saʊndz ɡreɪt haʊ əˈbaʊt ðɪs ˈwiːkend/", zh: "听起来不错。这周末怎么样？" },
      { en: "Works for me. I'll text you the details later.", ipa: "/wɜːrks fɔːr miː aɪl tekst juː ðə dɪˈteɪlz ˈleɪtər/", zh: "我可以。我晚点把细节发给你。" },
    ],
  },
  {
    id: 'restaurant',
    title: '生活 · 餐厅点餐',
    level: '初级',
    sentences: [
      { en: "Hi, could we see the menu, please?", ipa: "/haɪ kʊd wi siː ðə ˈmenjuː pliːz/", zh: "你好，可以给我们看一下菜单吗？" },
      { en: "Of course. Can I start you off with something to drink?", ipa: "/əv kɔːrs kæn aɪ stɑːrt juː ɔːf wɪð ˈsʌmθɪŋ tə drɪŋk/", zh: "当然。要先来点喝的吗？" },
      { en: "I'll have a sparkling water, and what do you recommend?", ipa: "/aɪl hæv ə ˈspɑːrklɪŋ ˈwɔːtər ænd wʌt duː juː ˌrekəˈmend/", zh: "我要一杯气泡水，你有什么推荐的吗？" },
      { en: "The grilled salmon is really popular today.", ipa: "/ðə ɡrɪld ˈsæmən ɪz ˈrɪli ˈpɑːpjələr təˈdeɪ/", zh: "今天的烤三文鱼很受欢迎。" },
      { en: "That sounds perfect. I'll go with that.", ipa: "/ðæt saʊndz ˈpɜːrfɪkt aɪl ɡoʊ wɪð ðæt/", zh: "听起来很棒，我就要那个。" },
    ],
  },
  {
    id: 'travel',
    title: '出行 · 机场与方向',
    level: '中级',
    sentences: [
      { en: "Excuse me, could you tell me where the boarding gate is?", ipa: "/ɪkˈskjuːz miː kʊd juː tel miː wer ðə ˈbɔːrdɪŋ ɡeɪt ɪz/", zh: "打扰一下，能告诉我登机口在哪里吗？" },
      { en: "Sure, gate twenty-two is just down the hall on your right.", ipa: "/ʃʊr ɡeɪt ˈtwenti tuː ɪz dʒʌst daʊn ðə hɔːl ɒn jʊr raɪt/", zh: "当然，22 号登机口就在走廊尽头右手边。" },
      { en: "Do you know if the flight is still on time?", ipa: "/duː juː noʊ ɪf ðə flaɪt ɪz stɪl ɒn taɪm/", zh: "你知道航班是否还准时吗？" },
      { en: "It's been delayed by about half an hour, unfortunately.", ipa: "/ɪts bɪn dɪˈleɪd baɪ əˈbaʊt hæf ən ˈaʊər ʌnˈfɔːrtʃənətli/", zh: "很遗憾，航班延误了大约半小时。" },
      { en: "No worries. Thanks for letting me know.", ipa: "/noʊ ˈwɜːriz θæŋks fɔːr ˈletɪŋ miː noʊ/", zh: "没关系，谢谢你告诉我。" },
    ],
  },
  {
    id: 'work',
    title: '职场 · 会议与协作',
    level: '中级',
    sentences: [
      { en: "Let's circle back to this after we've gathered more data.", ipa: "/lets ˈsɜːrkəl bæk tə ðɪs ˈæftər wiːv ˈɡæðərd mɔːr ˈdeɪtə/", zh: "等我们收集到更多数据后，再回头讨论这件事。" },
      { en: "I think we're on the same page about the priorities.", ipa: "/aɪ θɪŋk wɪr ɒn ðə seɪm peɪdʒ əˈbaʊt ðə praɪˈɔːrətiz/", zh: "我觉得我们在优先级上看法一致。" },
      { en: "Could you walk me through your reasoning here?", ipa: "/kʊd juː wɔːk miː θruː jʊr ˈriːzənɪŋ hɪr/", zh: "你能给我讲讲你这里的思路吗？" },
      { en: "Let me follow up with the team and get back to you.", ipa: "/let miː ˈfɒloʊ ʌp wɪð ðə tiːm ænd ɡet bæk tə juː/", zh: "我跟团队再确认一下，然后回复你。" },
      { en: "That makes sense. Let's move forward with it.", ipa: "/ðæt meɪks sens lets muːv ˈfɔːrwərd wɪð ɪt/", zh: "有道理，那我们就这样推进吧。" },
    ],
  },

  // ---- 美国实用系列：在美国日常高频用到的听说内容 ----
  {
    id: 'spelling-alphabet',
    title: '美国实用 · 电话拼写字母表',
    level: '实用',
    sentences: [
      { en: "A as in Apple.", ipa: "/eɪ æz ɪn ˈæpəl/", zh: "A，Apple 的 A。（在电话里报名字/邮箱时用）" },
      { en: "B as in Boy.", ipa: "/biː æz ɪn bɔɪ/", zh: "B，Boy 的 B。" },
      { en: "C as in Cat.", ipa: "/siː æz ɪn kæt/", zh: "C，Cat 的 C。" },
      { en: "D as in Dog.", ipa: "/diː æz ɪn dɔːɡ/", zh: "D，Dog 的 D。" },
      { en: "E as in Elephant.", ipa: "/iː æz ɪn ˈeləfənt/", zh: "E，Elephant 的 E。" },
      { en: "F as in Frank.", ipa: "/ef æz ɪn fræŋk/", zh: "F，Frank 的 F。" },
      { en: "G as in George.", ipa: "/dʒiː æz ɪn dʒɔːrdʒ/", zh: "G，George 的 G。" },
      { en: "H as in Henry.", ipa: "/eɪtʃ æz ɪn ˈhenri/", zh: "H，Henry 的 H。" },
      { en: "I as in Ice.", ipa: "/aɪ æz ɪn aɪs/", zh: "I，Ice 的 I。" },
      { en: "J as in John.", ipa: "/dʒeɪ æz ɪn dʒɑːn/", zh: "J，John 的 J。" },
      { en: "K as in King.", ipa: "/keɪ æz ɪn kɪŋ/", zh: "K，King 的 K。" },
      { en: "L as in Lion.", ipa: "/el æz ɪn ˈlaɪən/", zh: "L，Lion 的 L。" },
      { en: "M as in Mary.", ipa: "/em æz ɪn ˈmeri/", zh: "M，Mary 的 M。" },
      { en: "N as in Nancy.", ipa: "/en æz ɪn ˈnænsi/", zh: "N，Nancy 的 N。" },
      { en: "O as in Ocean.", ipa: "/oʊ æz ɪn ˈoʊʃən/", zh: "O，Ocean 的 O。" },
      { en: "P as in Peter.", ipa: "/piː æz ɪn ˈpiːtər/", zh: "P，Peter 的 P。" },
      { en: "Q as in Queen.", ipa: "/kjuː æz ɪn kwiːn/", zh: "Q，Queen 的 Q。" },
      { en: "R as in Robert.", ipa: "/ɑːr æz ɪn ˈrɑːbərt/", zh: "R，Robert 的 R。" },
      { en: "S as in Sam.", ipa: "/es æz ɪn sæm/", zh: "S，Sam 的 S。" },
      { en: "T as in Tom.", ipa: "/tiː æz ɪn tɑːm/", zh: "T，Tom 的 T。" },
      { en: "U as in Umbrella.", ipa: "/juː æz ɪn ʌmˈbrelə/", zh: "U，Umbrella 的 U。" },
      { en: "V as in Victor.", ipa: "/viː æz ɪn ˈvɪktər/", zh: "V，Victor 的 V。" },
      { en: "W as in William.", ipa: "/ˈdʌbəljuː æz ɪn ˈwɪljəm/", zh: "W，William 的 W。" },
      { en: "X as in X-ray.", ipa: "/eks æz ɪn ˈeksreɪ/", zh: "X，X-ray 的 X。" },
      { en: "Y as in Yellow.", ipa: "/waɪ æz ɪn ˈjeloʊ/", zh: "Y，Yellow 的 Y。" },
      { en: "Z as in Zebra.", ipa: "/ziː æz ɪn ˈziːbrə/", zh: "Z，Zebra 的 Z。" },
      { en: "Could you spell that for me, please?", ipa: "/kʊd juː spel ðæt fɔːr miː pliːz/", zh: "请帮我拼一下好吗？" },
      { en: "Sure — it's W as in William, A as in Apple, N as in Nancy, G as in George.", ipa: "/ʃʊr ɪts ˈdʌbəljuː æz ɪn ˈwɪljəm eɪ æz ɪn ˈæpəl en æz ɪn ˈnænsi dʒiː æz ɪn dʒɔːrdʒ/", zh: "好的——William 的 W，Apple 的 A，Nancy 的 N，George 的 G。（Wang）" },
    ],
  },
  {
    id: 'coffee-shop',
    title: '美国实用 · 咖啡店点单',
    level: '实用',
    sentences: [
      { en: "Hi, can I get a tall iced latte with oat milk?", ipa: "/haɪ kæn aɪ ɡet ə tɔːl aɪst ˈlɑːteɪ wɪð oʊt mɪlk/", zh: "你好，来一杯中杯冰拿铁，换燕麦奶。" },
      { en: "What size would you like — tall, grande, or venti?", ipa: "/wʌt saɪz wʊd juː laɪk tɔːl ˈɡrɑːndeɪ ɔːr ˈventi/", zh: "您要什么杯型——中杯、大杯还是超大杯？" },
      { en: "Could I get that with less ice, please?", ipa: "/kʊd aɪ ɡet ðæt wɪð les aɪs pliːz/", zh: "可以少冰吗？" },
      { en: "Can I get a name for the order? — Sure, it's Alan. A-L-A-N.", ipa: "/kæn aɪ ɡet ə neɪm fɔːr ðə ˈɔːrdər ʃʊr ɪts ˈælən/", zh: "取餐名怎么称呼？——Alan，A-L-A-N。" },
      { en: "For here or to go?", ipa: "/fɔːr hɪr ɔːr tə ɡoʊ/", zh: "堂食还是带走？" },
      { en: "Anything else? — That'll be it, thanks.", ipa: "/ˈeniθɪŋ els ˈðætəl biː ɪt θæŋks/", zh: "还要别的吗？——就这些，谢谢。" },
      { en: "Your total is six seventy-five. Tap or insert your card.", ipa: "/jʊr ˈtoʊtəl ɪz sɪks ˈsevənti faɪv tæp ɔːr ɪnˈsɜːrt jʊr kɑːrd/", zh: "一共 6.75 美元，刷卡或插卡。" },
      { en: "I'll have that ready for you at the end of the bar.", ipa: "/aɪl hæv ðæt ˈredi fɔːr juː æt ðə end əv ðə bɑːr/", zh: "做好后在吧台那头取。" },
    ],
  },
  {
    id: 'pharmacy',
    title: '美国实用 · 药房与看病',
    level: '实用',
    sentences: [
      { en: "Hi, I'm here to pick up a prescription for Wang.", ipa: "/haɪ aɪm hɪr tə pɪk ʌp ə prɪˈskrɪpʃən fɔːr wɑːŋ/", zh: "你好，我来取 Wang 的处方药。" },
      { en: "Can I have your date of birth, please?", ipa: "/kæn aɪ hæv jʊr deɪt əv bɜːrθ pliːz/", zh: "请告诉我您的出生日期。" },
      { en: "What do you recommend for a sore throat and a runny nose?", ipa: "/wʌt duː juː ˌrekəˈmend fɔːr ə sɔːr θroʊt ænd ə ˈrʌni noʊz/", zh: "嗓子疼、流鼻涕，你推荐什么药？" },
      { en: "I've had a fever since last night.", ipa: "/aɪv hæd ə ˈfiːvər sɪns læst naɪt/", zh: "我从昨晚开始发烧。" },
      { en: "Are you allergic to any medications?", ipa: "/ɑːr juː əˈlɜːrdʒɪk tə ˈeni ˌmedɪˈkeɪʃənz/", zh: "您对什么药物过敏吗？" },
      { en: "Take two tablets every six hours with food.", ipa: "/teɪk tuː ˈtæbləts ˈevri sɪks ˈaʊərz wɪð fuːd/", zh: "每六小时随餐服用两片。" },
      { en: "You can grab some ibuprofen in aisle five.", ipa: "/juː kæn ɡræb sʌm ˌaɪbjuːˈproʊfən ɪn aɪl faɪv/", zh: "布洛芬在五号货架，自己拿就行。" },
      { en: "Feel better soon!", ipa: "/fiːl ˈbetər suːn/", zh: "祝早日康复！" },
    ],
  },
  {
    id: 'numbers',
    title: '美国实用 · 数字·电话·金额',
    level: '实用',
    sentences: [
      { en: "My phone number is six one seven, five five five, zero one two nine.", ipa: "/maɪ foʊn ˈnʌmbər ɪz sɪks wʌn ˈsevən faɪv faɪv faɪv ˈzɪroʊ wʌn tuː naɪn/", zh: "我的电话是 617-555-0129。（美国电话按 3-3-4 分组读）" },
      { en: "That'll be twenty-four ninety-nine, please.", ipa: "/ˈðætəl biː ˈtwenti fɔːr ˈnaɪnti naɪn pliːz/", zh: "一共 24.99 美元。（美元金额常省略 dollars 和 point）" },
      { en: "My zip code is nine four one oh three.", ipa: "/maɪ zɪp koʊd ɪz naɪn fɔːr wʌn oʊ θriː/", zh: "我的邮编是 94103。（0 常读作 oh）" },
      { en: "The meeting is at three thirty p.m. on Tuesday the twelfth.", ipa: "/ðə ˈmiːtɪŋ ɪz æt θriː ˈθɜːrti piː em ɒn ˈtuːzdeɪ ðə twelfθ/", zh: "会议在周二 12 号下午三点半。" },
      { en: "I live at forty-two twenty-eight Oak Street, apartment three B.", ipa: "/aɪ lɪv æt ˈfɔːrti tuː ˈtwenti eɪt oʊk striːt əˈpɑːrtmənt θriː biː/", zh: "我住在橡树街 4228 号 3B 公寓。（门牌号两位两位读）" },
      { en: "It's about a fifteen-minute walk, maybe half a mile.", ipa: "/ɪts əˈbaʊt ə ˈfɪftiːn ˈmɪnɪt wɔːk ˈmeɪbi hæf ə maɪl/", zh: "走路大概十五分钟，差不多半英里。" },
      { en: "The flight leaves at seven oh five in the morning.", ipa: "/ðə flaɪt liːvz æt ˈsevən oʊ faɪv ɪn ðə ˈmɔːrnɪŋ/", zh: "航班早上 7:05 起飞。（7:05 读作 seven oh five）" },
      { en: "Your confirmation number is C as in Cat, seven, four, X as in X-ray, two.", ipa: "/jʊr ˌkɑːnfərˈmeɪʃən ˈnʌmbər ɪz siː æz ɪn kæt ˈsevən fɔːr eks æz ɪn ˈeksreɪ tuː/", zh: "您的确认码是 C74X2。（字母配合拼读词，数字逐个读）" },
    ],
  },
  {
    id: 'drive-thru',
    title: '美国实用 · 快餐 Drive-thru',
    level: '实用',
    sentences: [
      { en: "Hi, welcome in! What can I get started for you?", ipa: "/haɪ ˈwelkəm ɪn wʌt kæn aɪ ɡet ˈstɑːrtɪd fɔːr juː/", zh: "欢迎光临！想点些什么？（drive-thru 开场白）" },
      { en: "Can I get a number one combo with a Coke?", ipa: "/kæn aɪ ɡet ə ˈnʌmbər wʌn ˈkɑːmboʊ wɪð ə koʊk/", zh: "我要一号套餐，配可乐。（美国点餐直接报编号）" },
      { en: "Would you like to make that a large?", ipa: "/wʊd juː laɪk tə meɪk ðæt ə lɑːrdʒ/", zh: "要升级成大份吗？" },
      { en: "Could I also get a side of fries?", ipa: "/kʊd aɪ ˈɔːlsoʊ ɡet ə saɪd əv fraɪz/", zh: "再加一份薯条。" },
      { en: "Anything else for you today? — No, that's it, thanks.", ipa: "/ˈeniθɪŋ els fɔːr juː təˈdeɪ noʊ ðæts ɪt θæŋks/", zh: "还要别的吗？——没了，谢谢。" },
      { en: "Please pull up to the second window.", ipa: "/pliːz pʊl ʌp tə ðə ˈsekənd ˈwɪndoʊ/", zh: "请开到第二个窗口。（pull up = 把车开过去）" },
      { en: "Can I get some ketchup and napkins with that?", ipa: "/kæn aɪ ɡet sʌm ˈketʃəp ænd ˈnæpkɪnz wɪð ðæt/", zh: "给我一些番茄酱和纸巾。" },
      { en: "Here's your order — have a great day!", ipa: "/hɪrz jʊr ˈɔːrdər hæv ə ɡreɪt deɪ/", zh: "这是您的餐——祝您愉快！" },
    ],
  },
  {
    id: 'bank-dmv',
    title: '美国实用 · 银行与 DMV',
    level: '实用',
    sentences: [
      { en: "I'd like to open a checking account.", ipa: "/aɪd laɪk tə ˈoʊpən ə ˈtʃekɪŋ əˈkaʊnt/", zh: "我想开一个支票账户。（checking=日常账户，savings=储蓄账户）" },
      { en: "Is there a monthly fee for this account?", ipa: "/ɪz ðer ə ˈmʌnθli fiː fɔːr ðɪs əˈkaʊnt/", zh: "这个账户有月费吗？" },
      { en: "I'd like to deposit this check into my savings.", ipa: "/aɪd laɪk tə dɪˈpɑːzɪt ðɪs tʃek ˈɪntuː maɪ ˈseɪvɪŋz/", zh: "我想把这张支票存进储蓄账户。" },
      { en: "Could you help me set up direct deposit?", ipa: "/kʊd juː help miː set ʌp dəˈrekt dɪˈpɑːzɪt/", zh: "能帮我设置工资直存吗？（入职后常办）" },
      { en: "Your debit card will arrive in five to seven business days.", ipa: "/jʊr ˈdebɪt kɑːrd wɪl əˈraɪv ɪn faɪv tə ˈsevən ˈbɪznəs deɪz/", zh: "您的借记卡五到七个工作日寄到。" },
      { en: "I'm here to renew my driver's license.", ipa: "/aɪm hɪr tə rɪˈnuː maɪ ˈdraɪvərz ˈlaɪsəns/", zh: "我来更新驾照。" },
      { en: "Do you have an appointment, or are you a walk-in?", ipa: "/duː juː hæv ən əˈpɔɪntmənt ɔːr ɑːr juː ə wɔːk ɪn/", zh: "您有预约吗，还是现场排队？（walk-in=没预约直接来）" },
      { en: "Can I see two proofs of residency, please?", ipa: "/kæn aɪ siː tuː pruːfs əv ˈrezɪdənsi pliːz/", zh: "请出示两份住址证明。（水电账单、租约都算）" },
      { en: "Take a number and have a seat — we'll call you up.", ipa: "/teɪk ə ˈnʌmbər ænd hæv ə siːt wiːl kɔːl juː ʌp/", zh: "取个号请坐，到号会叫您。" },
      { en: "You passed! Your new license will come in the mail.", ipa: "/juː pæst jʊr nuː ˈlaɪsəns wɪl kʌm ɪn ðə meɪl/", zh: "通过了！新驾照会邮寄给您。" },
    ],
  },
  {
    id: 'apartment',
    title: '美国实用 · 租房与看房',
    level: '实用',
    sentences: [
      { en: "Hi, I'm calling about the two-bedroom apartment listed online.", ipa: "/haɪ aɪm ˈkɔːlɪŋ əˈbaʊt ðə tuː ˈbedruːm əˈpɑːrtmənt ˈlɪstɪd ˈɔːnlaɪn/", zh: "你好，我看到网上挂的两居室，来电咨询。" },
      { en: "Is it still available? Could I schedule a tour?", ipa: "/ɪz ɪt stɪl əˈveɪləbəl kʊd aɪ ˈskedʒuːl ə tʊr/", zh: "还在出租吗？能约个时间看房吗？（看房叫 tour）" },
      { en: "What's included in the rent — utilities or parking?", ipa: "/wʌts ɪnˈkluːdɪd ɪn ðə rent juːˈtɪlətiz ɔːr ˈpɑːrkɪŋ/", zh: "房租包含什么——水电网、车位吗？（utilities=水电煤网）" },
      { en: "It's two thousand a month with a one-month security deposit.", ipa: "/ɪts tuː ˈθaʊzənd ə mʌnθ wɪð ə wʌn mʌnθ sɪˈkjʊrəti dɪˈpɑːzɪt/", zh: "月租两千，押金一个月。" },
      { en: "Are pets allowed in the building?", ipa: "/ɑːr pets əˈlaʊd ɪn ðə ˈbɪldɪŋ/", zh: "楼里可以养宠物吗？" },
      { en: "There's in-unit laundry and a gym on the first floor.", ipa: "/ðerz ɪn ˈjuːnɪt ˈlɔːndri ænd ə dʒɪm ɒn ðə fɜːrst flɔːr/", zh: "户内带洗烘衣机，一楼有健身房。（in-unit laundry 是加分项）" },
      { en: "The lease is twelve months, starting August first.", ipa: "/ðə liːs ɪz twelv mʌnθs ˈstɑːrtɪŋ ˈɔːɡəst fɜːrst/", zh: "租约十二个月，八月一号起租。" },
      { en: "You'll need proof of income and a credit check to apply.", ipa: "/juːl niːd pruːf əv ˈɪnkʌm ænd ə ˈkredɪt tʃek tə əˈplaɪ/", zh: "申请需要收入证明，还要查信用。" },
      { en: "When would you be able to move in?", ipa: "/wen wʊd juː biː ˈeɪbəl tə muːv ɪn/", zh: "您什么时候能入住？" },
      { en: "I'll take it — where do I sign?", ipa: "/aɪl teɪk ɪt wer duː aɪ saɪn/", zh: "我租了——在哪里签字？" },
    ],
  },
  {
    id: 'reductions',
    title: '听力专项 · 连读与弱读',
    level: '实用',
    sentences: [
      { en: "I'm gonna head out in a couple minutes.", ipa: "/aɪm ˈɡɔːnə hed aʊt ɪn ə ˈkʌpəl ˈmɪnɪts/", zh: "我过几分钟就走。（gonna = going to，美语最高频弱读）" },
      { en: "Do you wanna grab a bite later?", ipa: "/duː juː ˈwɑːnə ɡræb ə baɪt ˈleɪtər/", zh: "待会想去吃点东西吗？（wanna = want to）" },
      { en: "I gotta get going, it's getting late.", ipa: "/aɪ ˈɡɑːtə ɡet ˈɡoʊɪŋ ɪts ˈɡetɪŋ leɪt/", zh: "我得走了，不早了。（gotta = got to）" },
      { en: "Lemme know if you need anything.", ipa: "/ˈlemi noʊ ɪf juː niːd ˈeniθɪŋ/", zh: "有需要就告诉我。（lemme = let me）" },
      { en: "Gimme a second, I'll be right there.", ipa: "/ˈɡɪmi ə ˈsekənd aɪl biː raɪt ðer/", zh: "稍等一下，我马上到。（gimme = give me）" },
      { en: "Whaddaya think about the new place?", ipa: "/ˈwʌdəjə θɪŋk əˈbaʊt ðə nuː pleɪs/", zh: "你觉得新地方怎么样？（whaddaya = what do you）" },
      { en: "It's kinda far, but sorta worth it.", ipa: "/ɪts ˈkaɪndə fɑːr bʌt ˈsɔːrtə wɜːrθ ɪt/", zh: "有点远，但也算值得。（kinda / sorta = kind of / sort of）" },
      { en: "I dunno, maybe we should ask someone.", ipa: "/aɪ dəˈnoʊ ˈmeɪbi wiː ʃʊd æsk ˈsʌmwʌn/", zh: "我不知道，要不问问人吧。（dunno = don't know）" },
      { en: "You shoulda seen the line at Costco.", ipa: "/juː ˈʃʊdə siːn ðə laɪn æt ˈkɑːstkoʊ/", zh: "你真该看看 Costco 排的队。（shoulda = should have）" },
      { en: "C'mon, it'll be fun — trust me.", ipa: "/kəˈmɑːn ˈɪtəl biː fʌn trʌst miː/", zh: "来嘛，会很好玩的——相信我。（c'mon = come on）" },
    ],
  },
  {
    id: 'small-talk',
    title: '地道口语 · 万能寒暄与回应',
    level: '实用',
    sentences: [
      { en: "Hey, how's it going? — Pretty good, how about you?", ipa: "/heɪ haʊz ɪt ˈɡoʊɪŋ ˈprɪti ɡʊd haʊ əˈbaʊt juː/", zh: "嘿，最近怎么样？——挺好的，你呢？（最常用的打招呼+回应）" },
      { en: "No worries at all.", ipa: "/noʊ ˈwɜːriz æt ɔːl/", zh: "完全没关系。（比 It's OK 更地道）" },
      { en: "My bad — I totally forgot about that.", ipa: "/maɪ bæd aɪ ˈtoʊtəli fərˈɡɑːt əˈbaʊt ðæt/", zh: "我的错——我完全忘了。（口语版 sorry）" },
      { en: "You're all set. Have a good one!", ipa: "/jʊr ɔːl set hæv ə ɡʊd wʌn/", zh: "都办好了。祝你愉快！（店员结账后最常说）" },
      { en: "I'm gonna grab a coffee real quick.", ipa: "/aɪm ˈɡɔːnə ɡræb ə ˈkɔːfi rɪl kwɪk/", zh: "我去快速买杯咖啡。（gonna、grab、real quick 都是高频口语）" },
      { en: "That works for me.", ipa: "/ðæt wɜːrks fɔːr miː/", zh: "我可以／这个安排没问题。" },
      { en: "Sounds good, I'll see you then.", ipa: "/saʊndz ɡʊd aɪl siː juː ðen/", zh: "好的，到时候见。" },
      { en: "Thanks so much — I really appreciate it.", ipa: "/θæŋks soʊ mʌtʃ aɪ ˈrɪli əˈpriːʃieɪt ɪt/", zh: "非常感谢——真的很感激。（比 thank you 更有诚意）" },
      { en: "Excuse me, sorry to bother you.", ipa: "/ɪkˈskjuːz miː ˈsɑːri tə ˈbɑːðər juː/", zh: "打扰一下，不好意思麻烦你。" },
      { en: "Take care! See you around.", ipa: "/teɪk ker siː juː əˈraʊnd/", zh: "保重！回头见。（告别的万能句）" },
    ],
  },
];
